export const ActionTypes = {
    USER_LOADING: "USER_LOADING",
    USER_LOADED: "USER_LOADED",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    GET_TRACKS : "GET_TRACKS",
    GET_ERRORS : 'GET_ERRORS',
    GET_ARTIST_DETAIL : 'GET_ARTIST_DETAIL',
    GET_ALBUMS : 'GET_ALBUMS',
    SET_UPLOAD_ALBUM : 'SET_UPLOAD_ALBUM',
    REMOVED_SET_ARTIST_DETAIL : 'REMOVED_SET_ARTIST_DETAIL',
    DELETE_TRACK : 'DELETE_TRACK',
    GET_PENDING_TRACKS : "GET_PENDING_TRACKS",
    APPROVE_TRACK : "APPROVE_TRACK",
    GET_ACTIVE_USERS : "GET_ACTIVE_USERS",
    GET_STAFFS : "GET_STAFFS",
    GET_GROUPS : "GET_GROUPS",
    GET_PERMISSIONS : "GET_PERMISSIONS",
    CREATE_GROUP : "CREATE_GROUP",
    ASSIGN_PERMISSION_TO_GROUP: "ASSIGN_PERMISSION_TO_GROUP",
    DELETE_GROUP:"DELETE_GROUP"
    
};