export const ActionTypes = {
    USER_LOADING: "USER_LOADING",
    USER_LOADED: "USER_LOADED",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    GET_ERRORS : 'GET_ERRORS',
    GET_ARTIST_DETAIL : 'GET_ARTIST_DETAIL',
    REMOVED_SET_ARTIST_DETAIL : 'REMOVED_SET_ARTIST_DETAIL',
};